"""
Django settings for cs412 project.

Generated by 'django-admin startproject' using Django 5.1.6.
"""

import os
import socket
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=d6gvu6*ce-wmlm=_clzc$kh^qb615!w-&83==&vi^0mey04ov'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 1) Include 'cs-webapps.bu.edu' for deployment
#    Optionally include '127.0.0.1' and 'localhost' for local dev.
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'cs-webapps.bu.edu',
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mini_fb',  # your custom app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cs412.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'mini_fb', 'templates'),
        ],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cs412.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True


# 2) Static and Media Files Configuration
#    (Used in local development and production)

# Where 'collectstatic' puts your files
STATIC_ROOT = BASE_DIR / 'staticfiles'
# The base URL for static files
STATIC_URL = '/static/'

# Where your local (dev) static files live
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media (if you have user-uploaded files)
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = 'media/'

# 3) Adjust URLs if you're on cs-webapps.bu.edu
CS_DEPLOYMENT_HOSTNAME = 'cs-webapps.bu.edu'
if socket.gethostname() == CS_DEPLOYMENT_HOSTNAME:
    # Replace 'username' with your BU username
    STATIC_URL = '/username/static/'
    MEDIA_URL = '/username/media/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
